Sprint 9 solution http api
Kreskowl/java-kanban pull request #5
Opened 2024-11-14 12:03 UTC by Kreskowl

Add http support, test new functionality

2024-11-14 12:07 UTC, Kreskowl commented
пойду себе батюшку на отпевание вызову Х_Х

2024-11-14 17:26 UTC, afomkina requested changes

2024-11-14 17:26 UTC, afomkina commented on src/ru/yandex/practicum/server/EpicsHandler.java
> +                sendResponse(exchange, 200, gson.toJson(epic.get()));
Прежде чем получать значение из `Optional` нужно убедиться, что он не пустой. Можно воспользоваться любым способом из [данной статьи](https://habr.com/ru/post/346782/#:~:text=%D0%9A%D0%B0%D0%BA%20%D0%BF%D0%BE%D0%BB%D1%83%D1%87%D0%B8%D1%82%D1%8C%20%D0%BE%D0%B1%D1%8A%D0%B5%D0%BA%D1%82%2C%20%D1%81%D0%BE%D0%B4%D0%B5%D1%80%D0%B6%D0%B0%D1%89%D0%B8%D0%B9%D1%81%D1%8F%20%D0%B2%20Optional%3F)

2024-11-14 17:26 UTC, afomkina commented on src/ru/yandex/practicum/server/EpicsHandler.java
> +            sendResponse(exchange, 200, gson.toJson(taskManager.getEpicsList()));
Задание со `"*"`:
Можно создать отдельное перечисление для HTTP кодов и использовать его вместо "голых" цифр. 
Так код будет выглядеть более читаемо и понятней. 
Примеры можно посмотреть в главе [Конструкторы, поля и методы перечисления](https://metanit.com/java/tutorial/3.8.php#:~:text=%D0%9A%D0%BE%D0%BD%D1%81%D1%82%D1%80%D1%83%D0%BA%D1%82%D0%BE%D1%80%D1%8B%2C%20%D0%BF%D0%BE%D0%BB%D1%8F%20%D0%B8%20%D0%BC%D0%B5%D1%82%D0%BE%D0%B4%D1%8B%20%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%81%D0%BB%D0%B5%D0%BD%D0%B8%D1%8F)

2024-11-14 17:26 UTC, afomkina commented on src/ru/yandex/practicum/server/HttpTaskServer.java
> +            serverCreateError.printStackTrace();
Печатать стектрейс - плохая практика, лучше расширить логирование

2024-11-14 17:26 UTC, afomkina commented on src/ru/yandex/practicum/server/SubTasksHandler.java
> +            sendResponse(exchange, 200, gson.toJson(subTask.get()));
Нужно проверить, что `Optional` не пустой, прежде чем доставать значение

2024-11-14 17:26 UTC, afomkina commented on src/ru/yandex/practicum/server/TasksHandler.java
> +            sendResponse(exchange, 200, gson.toJson(task.get()));
Нужно проверить, что `Optional` не пустой

2024-11-15 09:44 UTC, afomkina commented on src/ru/yandex/practicum/server/HttpTaskServer.java
> +           logger.log(Level.SEVERE, "Fail to create server on port " + PORT, serverCreateError);
👍

2024-11-15 09:44 UTC, afomkina approved these changes

2024-11-15 09:47 UTC, merged